language: java

jdk:
  - oraclejdk11

addons:
  sonarcloud:
    organization: "rolan2772-github"
    token:
      secure: $SONAR_CLOUD_KEY

env:
  - CI=false
script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.gradle'
    - '.gradle'

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: rolan-rock-paper-scissors